### PR TITLE
Update for purescript 0.7

### PR DESCRIPTION
**Pull request by garyb**

### CODE REVIEW

**Comment by garyb** [comment]
Can you make a `v0.3.0` release for this please? Thanks!

**Comment by themoritz** [comment]
@garyb can you keep the `0.7-updates` branch for a while since it's still referenced by purescript-css?

**Comment by garyb** [comment]
There's a PR open for `purescript-css` that will solve that soon, for now if you install `purescript-nonempty-array#68d6e04cd1874f01489a1de4b7dca5c7186f88d0` first with bower, you can then force that choice using the resolutions thing.

**Comment by themoritz** [comment]
That helps, thanks!

**Comment by stevejb71** [comment]
I've registered purescript-nonempty-arrays to version 0.3.0 for PS 0.7.

**Pull request merged**
